eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
#      preferIpAddress: true
spring:
  application:
    name: Album-Service
  datasource:
    url: "jdbc:mysql://localhost:3306/album-inventory-service"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'password'
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 0
springdoc:
  swagger-ui:
    path: "http://swagger-ui.html"