eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
spring:
  application:
    name: User-Service
  datasource:
    url: "jdbc:mysql://localhost:3306/rocknrollalbumart"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'password'
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
#  thymeleaf:
#    prefix: classpath:/templates/user_ThymeLeafTemplates/
server:
  port: 8083
springdoc:
  swagger-ui:
    path: "http://swagger-ui.html"
